### PR TITLE
Try going back to noarch

### PR DESCRIPTION
**Pull request by thewchan**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by thewchan** [comment]
@conda-forge-admin please rerender

**Comment by thewchan** [comment]
Noarch works; we're back to a normal python build, but we'll just have to deal with `numpy >=1.14` for all python versions.

**Comment by thewchan** [comment]
@darynwhite

**Comment by thewchan** [comment]
I'll merge this if you have no objection

**Comment by darynwhite** [comment]
Looks good to me!

**Comment by darynwhite** [comment]
Will close #41

**Pull request merged**
